/*
 * Runs on Netlify before publishing (see netlify.toml).
 * Reads PUBLIC Supabase settings from environment variables and writes js/config.js.
 *
 *   SUPABASE_URL       e.g. https://abcdxyz.supabase.co
 *   SUPABASE_ANON_KEY  the "anon" / "publishable" key  (NEVER the service_role / secret key)
 */
const fs = require('fs');
const path = require('path');

const target = path.join(__dirname, 'js', 'config.js');
const url = (process.env.SUPABASE_URL || '').trim();
const key = (process.env.SUPABASE_ANON_KEY || '').trim();

function fail(message) {
  console.error('\n[build-config] ERROR: ' + message + '\n');
  process.exit(1);
}

if (!url || !key) {
  const existing = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : '';
  if (existing && !/YOUR-/.test(existing)) {
    console.log('[build-config] No env vars set; using the values already in js/config.js.');
    process.exit(0);
  }
  fail('Set SUPABASE_URL and SUPABASE_ANON_KEY in Netlify (Site configuration > Environment variables), then redeploy.');
}

if (!/^https:\/\/[a-z0-9-]+\.supabase\.(co|in)\/?$/i.test(url)) {
  fail('SUPABASE_URL should look like https://YOUR-PROJECT-REF.supabase.co');
}

// Safety check: refuse secret / service-role keys so they can never reach the browser.
if (/^sb_secret_/i.test(key)) fail('That looks like a SECRET key. Use the anon / publishable key instead.');
try {
  const parts = key.split('.');
  if (parts.length === 3) {
    const payload = JSON.parse(Buffer.from(parts[1], 'base64url').toString('utf8'));
    if (payload.role === 'service_role') fail('That is the service_role key. Use the anon key instead.');
  }
} catch (e) { /* not a JWT (new-style publishable key); nothing more to check */ }

const output =
  '// Generated by build-config.js from Netlify environment variables.\n' +
  'window.CE_CONFIG = ' + JSON.stringify({ SUPABASE_URL: url.replace(/\/$/, ''), SUPABASE_ANON_KEY: key }, null, 2) + ';\n';
fs.writeFileSync(target, output);
console.log('[build-config] js/config.js written.');
